### ISSUE TITLE
カーソル位置と内部バッファポインタの連動について設計する

### ISSUE THREAD

**Issue by akif999** [akif999/kennel#7]
連動処理を上手く設計しないと様々な操作が辛くなる見込みであるため。

**Comment by AKIF999** [comment]
LineLengthをScrnBufferのメンバへ追加。

* カーソルの行末ガードをLineLengthで行う
* カーソルの行末から次の行頭への移動をLineLengthで行う
* カーソルの行頭から前の行末への移動をLineLengthで行う

**Comment by AKIF999** [comment]
bufferパッケージ内のメソッドで、カーソル位置を内部バッファ位置へ変換するように試作する。

**Comment by akif999** [comment]
設計からリライトしたためClose。
